version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:14.5
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PGDATA:/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: